# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Getting-Started.gitlab-ci.yml

# This is a sample GitLab CI/CD configuration file that should run without any modifications.
# It demonstrates a basic 3 stage CI/CD pipeline. Instead of real tests or scripts,
# it uses echo commands to simulate the pipeline execution.
#
# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.
#
# For more information, see: https://docs.gitlab.com/ee/ci/yaml/index.html#stages

cache:
  key: ${CI_PROJECT_ID}
  paths:
    - .gradle/

stages:
  - push
  - detekt

push:stable:
  stage: push
  # Set up the docker container for build docker images
  image: docker:stable-dind
  only:
    - stable
  tags: 
    - catm-dev
  image: ubuntu:latest
  before_script:
  - apt update && apt install -y openssh-client git
  script:
  - mkdir ~/.ssh/ && touch ~/.ssh/known_hosts && touch ~/.ssh/config 
  - ssh-keyscan -t rsa gitflic.ru >> ~/.ssh/known_hosts && echo -e "Host alias gitflic.ru\nPubkeyAcceptedKeyTypes=+ssh-rsa" > ~/.ssh/config
  - echo "$SSH_PRIVATE_KEY" >> ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
  - git switch stable
  - git remote set-url origin git@gitflic.ru:catm/android-app.git
  - git push -u origin stable

detekt:
  before_script:
  - export GRADLE_USER_HOME=$(pwd)/.gradle
  - chmod +x ./gradlew
  image: jangrewe/gitlab-ci-android
  stage: detekt
  script:
    - ./gradlew detekt
    
