# https://github.com/detekt/detekt/blob/main/detekt-core/src/main/resources/default-detekt-config.yml
config:
  validation: true
  # when writing own rules with new properties, exclude the property path e.g.: 'my_rule_set,.*>.*>[my_property]'
  excludes: 'mb-detekt-rules,.*>.*>[screenParentClasses]'

complexity:
  ComplexCondition:
    threshold: 6
  ComplexMethod:
    threshold: 20
    ignoreSingleWhenExpression: true
  LargeClass:
    excludes: '**/*AnalyticsSpec*.kt'
  LongMethod:
    excludes: [ '**/*AnalyticsSpec*.kt', '**/*AccountsAnalyticsSpec*.kt' ]
  LongParameterList:
    active: false
  TooManyFunctions:
    active: false

exceptions:
  PrintStackTrace:
    active: false
  RethrowCaughtException:
    active: false
  SwallowedException:
    active: false
  ThrowingExceptionsWithoutMessageOrCause:
    active: false
  ThrowingNewInstanceOfSameException:
    active: false
  TooGenericExceptionThrown:
    excludes: '**/WireMockAuthorizedTest.kt'

formatting:
  ImportOrdering:
    active: false
  Indentation:
    active: false
  MaximumLineLength:
    maxLineLength: 160
  NoConsecutiveBlankLines:
    excludes: '**/*AnalyticsSpec*.kt'
  SpacingAroundColon:
    excludes: '**/*AnalyticsSpec*.kt'

naming:
  ConstructorParameterNaming:
    active: false
  MemberNameEqualsClassName:
    active: false

performance:
  ArrayPrimitive:
    excludes: '**/*AnalyticsSpec*.kt'

potential-bugs:
  ImplicitDefaultLocale:
    active: false

style:
  ForbiddenComment:
    active: false
  FunctionOnlyReturningConstant:
    ignoreAnnotated:
      - 'Provides'
  LoopWithTooManyJumpStatements:
    active: false
  MagicNumber:
    excludes: [ '**/test/**', '**/androidTest/**', '**android-test**', '**/*.Test.kt', '**/*.Spec.kt', '**/*.Spek.kt' ]
  MaxLineLength:
    maxLineLength: 160
    excludes: '**/*AnalyticsSpec*.kt'
  ReturnCount:
    max: 3
  SerialVersionUIDInSerializableClass:
    active: false
  UnnecessaryAbstractClass:
    active: false
  UnusedPrivateMember:
    active: false
  WildcardImport:
    excludeImports:
      - 'kotlinx.android.synthetic.*'
